## Import Pytorch
Check if Pytorch is available in the environment.

In [1]:
import torch
x = torch.rand(5, 3)
print(x)

tensor([[0.1491, 0.6564, 0.1395],
        [0.9654, 0.5536, 0.9790],
        [0.5554, 0.3806, 0.3780],
        [0.7797, 0.6439, 0.9923],
        [0.6004, 0.6136, 0.2194]])


In [3]:
torch.__version__

'2.5.1+cu124'

## Tensor
Tensors are the fundamental building block of machine learning.
Their job is to represent data in a numerical way.

### Key learning points
- [Data types](https://pytorch.org/docs/stable/tensors.html#data-types)
- Initialize tensor of different shapes
- Manipulate tensor

#### Different Shapes of Tensor

| Name   | What is it?                                                                 | Number of dimensions                                                                 | Lower or upper (usually/example)                                                                 |
|--------|-----------------------------------------------------------------------------|--------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|
| scalar | a single number                                                             | 0                                                                                    | Lower (a)                                                                                        |
| vector | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1                                                                                    | Lower (y)                                                                                        |
| matrix | a 2-dimensional array of numbers                                            | 2                                                                                    | Upper (Q)                                                                                        |
| tensor | an n-dimensional array of numbers                                           | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (X)                                                                                        |

In [4]:
# Create a tensor
# scalar
a = torch.tensor(1.0)

# vector
y = torch.tensor([1.0, 2.0, 3.0, 4.0])

# matrix
Q = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# N-dimensional tensor
X = torch.tensor([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])

# random tensor
R = torch.rand(size=(3, 4))

# all zeros tensor
Z = torch.zeros(size=(3, 4))

# all ones tensor
O = torch.ones(size=(3, 4))

# use arange to create a tensor
zero_to_ten = torch.arange(start=0, end=10, step=2)

# use zeros_like to create a tensor
zeros_tensor = torch.zeros_like(zero_to_ten)

# print the tensor
print("scalar:", a)
print("vector: ", y)
print("matrix:", Q)
print("tensor:", X)
print("random tensor:", R)
print("all zeros tensor:", Z)
print("all ones tensor:", O)
print("zero to ten:", zero_to_ten)
print("zeros tensor:", zeros_tensor)

scalar: tensor(1.)
vector:  tensor([1., 2., 3., 4.])
matrix: tensor([[1., 2.],
        [3., 4.]])
tensor: tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
random tensor: tensor([[0.8365, 0.4091, 0.5110, 0.6634],
        [0.2815, 0.1100, 0.4280, 0.1230],
        [0.8911, 0.0910, 0.4915, 0.1522]])
all zeros tensor: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
all ones tensor: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
zero to ten: tensor([0, 2, 4, 6, 8])
zeros tensor: tensor([0, 0, 0, 0, 0])


#### Get the Structure of Tensor
- `.ndim`
- `.item`
- `.shape`

In [5]:
# dimensions of the tensor
print("scalar:", a.ndim)
print("vector:", y.ndim)
print("matrix:", Q.ndim)
print("tensor:", X.ndim)

scalar: 0
vector: 1
matrix: 2
tensor: 3


#### Data Types
Here we specify data type when creating a tensor.

In [6]:
# Create a tensor without specifying the data type
dtype_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0],
                            dtype=None,
                            device=None,
                            requires_grad=False)
print("Data type: ", dtype_tensor.dtype)

Data type:  torch.float32


In [7]:
import math

print(math.pi, math.e)

# Create a tensor with a specific data type of 32-bit floating point
float32_tensor = torch.tensor([math.pi, math.e],
                              dtype=torch.float32,
                              device=None,
                              requires_grad=False)

# print the difference between math.pi and its representation in the tensor
print("diff for pi: ", math.pi - float32_tensor[0].item())

float32_tensor[0].item(), float32_tensor.element_size(), float32_tensor.dtype, float32_tensor.device

3.141592653589793 2.718281828459045
diff for pi:  -8.742278012618954e-08


(3.1415927410125732, 4, torch.float32, device(type='cpu'))

In [8]:
import math

print(math.pi, math.e)

# Create a tensor with a specific data type of 64-bit floating point
float64_tensor = torch.tensor([math.pi, math.e],
                              dtype=torch.float64,
                              device=None,
                              requires_grad=False)

# print the difference between math.pi and its representation in the tensor
print("diff for pi: ", math.pi - float64_tensor[0].item())

float64_tensor[0].item(), float64_tensor.element_size(), float64_tensor.dtype, float64_tensor.device

3.141592653589793 2.718281828459045
diff for pi:  0.0


(3.141592653589793, 8, torch.float64, device(type='cpu'))

## Manipulate Tensors
- addition
- subtraction
- multiplication (element-wise)
- division
- matrix multiplication

In [9]:
## addition
tensor = torch.tensor([1.0, 2.0, 3.0, 4.0])
print("tensor + tensor = ", tensor + tensor)
print("tensor + 10 = ", tensor + 10)

## subtraction
print("tensor - tensor = ", tensor - tensor)
print("tensor - 10 = ", tensor - 10)

## multiplication (element-wise)
print("tensor * tensor = ", tensor * tensor)
print("tensor * 10 = ", tensor * 10)
print("torch.mul(tensor, 10) = ", torch.mul(tensor, 10))

## division
print("tensor / tensor = ", tensor / tensor)
print("tensor / 10 = ", tensor / 10)

## dot product
print("torch.matmul(tensor, tensor) = ", torch.matmul(tensor, tensor))

tensor + tensor =  tensor([2., 4., 6., 8.])
tensor + 10 =  tensor([11., 12., 13., 14.])
tensor - tensor =  tensor([0., 0., 0., 0.])
tensor - 10 =  tensor([-9., -8., -7., -6.])
tensor * tensor =  tensor([ 1.,  4.,  9., 16.])
tensor * 10 =  tensor([10., 20., 30., 40.])
torch.mul(tensor, 10) =  tensor([10., 20., 30., 40.])
tensor / tensor =  tensor([1., 1., 1., 1.])
tensor / 10 =  tensor([0.1000, 0.2000, 0.3000, 0.4000])
torch.matmul(tensor, tensor) =  tensor(30.)


In [10]:
%%time
print("torch.matmul", torch.matmul(tensor, tensor))

print("tensor @ tensor = ", tensor @ tensor)

torch.matmul tensor(30.)
tensor @ tensor =  tensor(30.)
CPU times: user 1.32 ms, sys: 19 μs, total: 1.34 ms
Wall time: 915 μs


In [11]:
# the inner dimensions of the two matrices must be the same
# the resulting matrix will have the shape of the outer dimensions
# i.e. (2, 3) @ (3, 2) = (2, 2)
tensor_mat = torch.rand(2, 3) @ torch.rand(3, 4)
print("(2,3) @ (3,2) = ", tensor_mat)
print("shape: ", tensor_mat.shape)

(2,3) @ (3,2) =  tensor([[0.7828, 0.7684, 1.1607, 0.8876],
        [0.5300, 0.5351, 0.7048, 0.7582]])
shape:  torch.Size([2, 4])


In [12]:
# transpose
tensorA = torch.tensor([[1, 2], [3, 4], [5, 6]])
print("tensorA: ", tensorA, "shape: ", tensorA.shape)
print("tensorA.T: ", tensorA.T, "shape: ", tensorA.T.shape)
print("tensorA.t(): ", tensorA.t(), "shape: ", tensorA.t().shape)

tensorA:  tensor([[1, 2],
        [3, 4],
        [5, 6]]) shape:  torch.Size([3, 2])
tensorA.T:  tensor([[1, 3, 5],
        [2, 4, 6]]) shape:  torch.Size([2, 3])
tensorA.t():  tensor([[1, 3, 5],
        [2, 4, 6]]) shape:  torch.Size([2, 3])


In [15]:
# find the max, min, mean, and sum of the tensor
print("max: ", tensor.max())
print("min: ", tensor.min())
print("mean: ", tensor.mean())

max:  tensor(4.)
min:  tensor(1.)
mean:  tensor(2.5000)


In [3]:
# the following code will end up with a RuntimeError
# RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long
tensor_int64 = torch.tensor([1, 2, 3, 4], dtype=torch.int64)
# print("mean: ", tensor_int64.mean())

# to fix the error, convert the tensor to a floating point tensor
tensor_int64.type(torch.float64).mean()

tensor(2.5000, dtype=torch.float64)

In [ ]:
# reshape the tensor
tensor = torch.arange(9)
print("tensor: ", tensor)
print("tensor.reshape(3, 3): ", tensor.reshape(3, 3))

# change the view
z = tensor.view(3, 3)
print("z: ", z)
print("tensor: ", tensor)

# z and tensor share the same memory
z[0, 0] = -1
print("z: ", z)
print("tensor: ", tensor)

tensor:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor.reshape(3, 3):  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
z:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
z:  tensor([[-1,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]])
tensor:  tensor([-1,  1,  2,  3,  4,  5,  6,  7,  8])


In [11]:
# stack
x = torch.randn(2, 3)
y = torch.randn(2, 3)
print("x: ", x)
print("y: ", y)

x:  tensor([[-1.2129,  0.5628, -0.1500],
        [ 0.6058, -0.3978,  0.3751]])
y:  tensor([[ 0.0060, -0.2693, -1.6171],
        [ 0.5033,  0.0055,  1.5146]])


In [ ]:
# stack along the first dimension
print(torch.stack((x, y), dim=0))
print(torch.stack([x, y]))

# stack along the second dimension
print(torch.stack((x, y), dim=1))

# stack along the third dimension
print(torch.stack((x, y), dim=2))
print(torch.stack((x, y), dim=-1))


tensor([[[-1.2129,  0.5628, -0.1500],
         [ 0.6058, -0.3978,  0.3751]],

        [[ 0.0060, -0.2693, -1.6171],
         [ 0.5033,  0.0055,  1.5146]]])
tensor([[[-1.2129,  0.5628, -0.1500],
         [ 0.0060, -0.2693, -1.6171]],

        [[ 0.6058, -0.3978,  0.3751],
         [ 0.5033,  0.0055,  1.5146]]])
tensor([[[-1.2129,  0.0060],
         [ 0.5628, -0.2693],
         [-0.1500, -1.6171]],

        [[ 0.6058,  0.5033],
         [-0.3978,  0.0055],
         [ 0.3751,  1.5146]]])
tensor([[[-1.2129,  0.0060],
         [ 0.5628, -0.2693],
         [-0.1500, -1.6171]],

        [[ 0.6058,  0.5033],
         [-0.3978,  0.0055],
         [ 0.3751,  1.5146]]])
tensor([[[-1.2129,  0.5628, -0.1500],
         [ 0.6058, -0.3978,  0.3751]],

        [[-1.2129,  0.5628, -0.1500],
         [ 0.6058, -0.3978,  0.3751]]])
